version: '3'
services:
    db:
        image: uuovv/dbserver
        expose:
            - "5432"
        environment:
            - POSTGRES_PASSWORD=postgres
    web:
        image: uuovv/webserver
        ports:
            - "2000:2000"
        environment:
            - DBNAME=gruzdev_2
            - DB_USER=web_server_gruzdev
            - DB_HOST=db
            - DB_PORT=5432
            - DB_PASSWORD=gruzdev_2
                      
            - SERVER_HOST=web
            - SERVER_PORT=2000

            - WAIT_S=5