apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-deployment
  labels:
    app: main-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
      - name: main-app
        image: gruzdev/hse:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: main-app-service
spec:
  type: NodePort
  selector:
    app: main-app
  ports:
    - name: main-app
      protocol: TCP
      port: 8080
      targetPort: 8080
