apiVersion: v1
kind: Service
metadata:
  name: main-app
spec:
  selector:
    app: main-app--service
  ports:
    - name: main-app--service
      protocol: TCP
      port: 8080
      targetPort: 8080
